// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://thquljwnoewinxxvlmki.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRocXVsandub2V3aW54eHZsbWtpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzMzAwNDUsImV4cCI6MjA1OTkwNjA0NX0.oGQljmBZvMaCFR7wycIud1Wx2W6_jRQUfCXNdVGp4kQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);